# .github/workflows/build-ayugram.yml

name: Build and Package AyuGram for Linux

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (Release is recommended for packaging)'
        required: true
        type: choice
        default: 'Release'
        options:
        - Release
        - Debug

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    
    env:
      BUILD_TYPE: ${{ github.event.inputs.build_type || 'Release' }}

    steps:
      - name: Checkout AyuGram source code
        uses: actions/checkout@v4
        with:
          repository: AyuGram/AyuGramDesktop
          path: tdesktop
          submodules: 'recursive'

      - name: Build AyuGram with Docker (${{ env.BUILD_TYPE }})
        id: build
        working-directory: ./tdesktop
        run: |
          DOCKER_ARGS="--rm -u $(id -u):$(id -g) -v $PWD:/usr/src/tdesktop"

          if [ "${{ env.BUILD_TYPE }}" == "Debug" ]; then
            DOCKER_ARGS="$DOCKER_ARGS -e CONFIG=Debug"
          fi

          # 执行 Docker 构建命令
          docker run $DOCKER_ARGS \
            ghcr.io/telegramdesktop/tdesktop/centos_env:latest \
            /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
            -D TDESKTOP_API_ID=2040 \
            -D TDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627 \
            -D DESKTOP_APP_USE_PACKAGED=ON \
            -D CPACK_PACKAGE_VENDOR="AyuGram" \
            -D CPACK_PACKAGE_DESCRIPTION="Desktop Telegram client with good customization and Ghost mode" \
            -D CPACK_DEBIAN_PACKAGE_MAINTAINER="AyuGram Team"

      - name: Strip binary to reduce size (Release only)
        if: env.BUILD_TYPE == 'Release'
        run: |
          echo "Stripping the binary to reduce its size..."
          strip ./tdesktop/out/${{ env.BUILD_TYPE }}/AyuGram
          echo "Binary stripped."
          ls -lh ./tdesktop/out/${{ env.BUILD_TYPE }}/AyuGram

      - name: Create Linux Packages using CPack
        if: env.BUILD_TYPE == 'Release' # 打包通常只针对 Release 版本
        working-directory: ./tdesktop/out
        run: |
          echo "Running CPack to generate DEB..."
          # -G <Generator> 用于指定包格式
          cpack -G "DEB"
          
          echo "Listing generated packages:"
          ls -l ./*.{deb}

      - name: Upload Linux Packages as Artifacts
        if: env.BUILD_TYPE == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: Ayugram-Linux-Packages
          # 上传当前目录下的所有 .deb文件
          path: ./tdesktop/out/*.{deb}
          retention-days: 14
