# .github/workflows/build-and-release.yml

name: Build and Release AyuGram for Linux

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 5.16.3). Required for Release builds.'
        required: false
      commit_sha:
        description: 'Commit SHA or Tag to build from (e.g., v5.16.3). Defaults to "dev" branch of upstream.'
        required: false
        default: 'dev'
      build_type:
        description: 'Build type (Release or Debug)'
        required: true
        type: choice
        default: 'Release'
        options:
        - Release
        - Debug

permissions:
  contents: write

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Build Variables
        id: setup_vars
        run: |
          VERSION="${{ github.event.inputs.version }}"
          BUILD_TYPE="${{ github.event.inputs.build_type }}"
          
          if [ "$BUILD_TYPE" == "Release" ]; then
            BINARY_PATH="./tdesktop/out/Release/AyuGram"
            if [ -n "$VERSION" ]; then
              # 正确的语法: 写入 GITHUB_OUTPUT 文件
              echo "VERSION_TAG=v${VERSION}-linux" >> $GITHUB_OUTPUT
              echo "RELEASE_NAME=AyuGram v${VERSION} (Linux Build)" >> $GITHUB_OUTPUT
              echo "ASSET_NAME=AyuGram-${VERSION}-linux-x64" >> $GITHUB_OUTPUT
            fi
          else
            BINARY_PATH="./tdesktop/out/Debug/AyuGram"
          fi
          
          # 使用 GITHUB_ENV 来设置后续步骤的环境变量
          echo "BINARY_PATH=$BINARY_PATH" >> $GITHUB_ENV
          echo "Binary path set to: $BINARY_PATH"

      - name: Checkout AyuGram source code
        uses: actions/checkout@v4
        with:
          repository: AyuGram/AyuGramDesktop
          ref: ${{ github.event.inputs.commit_sha }}
          path: tdesktop
          submodules: 'recursive'

      - name: Build AyuGram with Docker
        working-directory: ./tdesktop
        run: |
          DOCKER_ARGS="--rm -u $(id -u):$(id -g) -v $PWD:/usr/src/tdesktop"
          BUILD_TYPE_ARG="-D CMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }}"
          docker run $DOCKER_ARGS \
            ghcr.io/telegramdesktop/tdesktop/centos_env:latest \
            /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
            -D TDESKTOP_API_ID=2040 \
            -D TDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627 \
            $BUILD_TYPE_ARG

      - name: Check if binary exists
        id: check_file
        run: |
          if [ -f "${{ env.BINARY_PATH }}" ]; then
            echo "Binary found at ${{ env.BINARY_PATH }}"
            # 正确的语法: 写入 GITHUB_OUTPUT 文件
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "::error::Binary NOT found at ${{ env.BINARY_PATH }}. Build might have failed."
            # 正确的语法: 写入 GITHUB_OUTPUT 文件
            echo "exists=false" >> $GITHUB_OUTPUT
            exit 1 # 如果文件不存在，直接让 Job 失败
          fi
          
      - name: Strip binary to reduce size
        if: github.event.inputs.build_type == 'Release'
        run: |
          echo "Stripping the release binary..."
          strip "${{ env.BINARY_PATH }}"
          ls -lh "${{ env.BINARY_PATH }}"

      - name: Create GitHub Release
        if: github.event.inputs.build_type == 'Release' && github.event.inputs.version != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.setup_vars.outputs.VERSION_TAG }}
          release_name: ${{ steps.setup_vars.outputs.RELEASE_NAME }}
          body: |
            Automated Linux build for AyuGram **v${{ github.event.inputs.version }}**.
            Triggered by upstream release: `AyuGram/AyuGramDesktop@${{ github.event.inputs.commit_sha }}`
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: steps.create_release.outputs.upload_url != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BINARY_PATH }}
          asset_name: ${{ steps.setup_vars.outputs.ASSET_NAME }}
          asset_content_type: application/octet-stream
          
      - name: Upload Debug Artifact
        if: github.event.inputs.build_type == 'Debug'
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-Debug-Build-${{ github.run_id }}
          path: ${{ env.BINARY_PATH }}
