# .github/workflows/build-ayugram.yml

name: Build AyuGram for Linux

on:
  # 允许手动从 GitHub Actions 页面触发此工作流
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        type: choice
        default: 'Release'
        options:
        - Release
        - Debug
  # 也可以在推送到主分支时自动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 将构建类型设置为环境变量，方便后续步骤使用
    env:
      BUILD_TYPE: ${{ github.event.inputs.build_type || 'Release' }}

    steps:
      - name: Checkout AyuGram source code
        uses: actions/checkout@v4
        with:
          # 从官方 AyuGram 仓库克隆代码
          repository: AyuGram/AyuGramDesktop
          # 将代码检出到 'tdesktop' 目录，与指南保持一致
          path: tdesktop
          # 递归克隆子模块，等同于 git clone --recursive
          submodules: 'recursive'

      - name: Set up Python and install poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install poetry
        run: pipx install poetry

      - name: Prepare build environment
        working-directory: ./tdesktop
        run: ./Telegram/build/prepare/linux.sh

      - name: Build AyuGram (${{ env.BUILD_TYPE }})
        working-directory: ./tdesktop
        run: |
          # 准备 Docker 命令的参数
          DOCKER_ARGS="--rm -u $(id -u):$(id -g) -v $PWD:/usr/src/tdesktop"

          # 如果是 Debug 构建，添加 -e CONFIG=Debug
          if [ "${{ env.BUILD_TYPE }}" == "Debug" ]; then
            DOCKER_ARGS="$DOCKER_ARGS -e CONFIG=Debug"
          fi

          # 执行 Docker 构建命令
          # 注意：这里使用了公开的测试 API ID 和 HASH。
          # 在生产或个人使用中，建议替换为您自己的密钥，并使用 GitHub Secrets 存储。
          docker run $DOCKER_ARGS \
            ghcr.io/telegramdesktop/tdesktop/centos_env:latest \
            /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
            -D TDESKTOP_API_ID=2040 \
            -D TDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627

      - name: Strip binary to reduce size (Release only)
        # 仅在 Release 构建时执行
        if: env.BUILD_TYPE == 'Release'
        run: |
          echo "Stripping the binary to reduce its size..."
          strip ./tdesktop/out/AyuGram
          echo "Binary stripped."
          ls -lh ./tdesktop/out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # 根据构建类型命名产物
          name: Ayugram-Linux-${{ env.BUILD_TYPE }}
          # 上传包含所有构建结果的 out 目录
          path: ./tdesktop/out/
          # 产物保留时间（天）
          retention-days: 7
